bracn-defaults:
  main:
    environment: exercise-map-env
    group_suffix: null
global:
  application_name: Exercise-Map
  branch: null
  default_ec2_keyname: primary
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
